micronaut:
  application:
    name: system-team-micronaut-demo
  server:
    port: 8080
  metrics:
    enabled: true

micrometer:
  observation:
    enabled: true
    http:
      server:
        enabled: true
      client:
        enabled: true

endpoints:
  all:
    enabled: true
    sensitive: false
